import AuthWrapper from "@/components/auth/AuthWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/reusable/SideBar";
import Header from "@/components/reusable/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidebar />
        <div className="flex flex-col flex-1 overflow-hidden">
          <div className="ml-64 p-6 h-[calc(100vh-64px)] overflow-y-auto">
          <Header />
            <AuthWrapper>{children}</AuthWrapper>
          </div>
        </div>
      </body>
    </html>
  );
}
